### PR TITLE
Add Help file and make small changes

### PR DESCRIPTION
**Pull request by randrescastaneda**
Hey JP, 
I think your package is awesome. Please take a look at the contributions that I made. 
1. Add option to create help file templates. 
2. Create help file for your package. (It is still missing detail explanation of options)
3. Make small modifications to the main ado file.

### CODE REVIEW

**Comment by jpazvd** [comment]
Thanks Andres, 

I will try to bring your suggestions into the dev branch.  I am still trying to figure out how to use this features.

One additional feature that could be useful is to auto generated a README.md from the HLP file (and vice-versa). If we have a README.md we can can generate a Stata HLP file.

I would like to figure how to bring your suggestions back into the main file. 

Best,

JP

**Review by jpazvd — COMMENTED** [review]
I think we should keep version mandatory. It is just good practice.
Yes, I can see prefix and path been optional.

**Review by jpazvd — COMMENTED** [review]
The name of the contributor needs to update (be appended) at the README.md.

**Review by jpazvd — COMMENTED** [review]
what is the problem of the return add? it is useful to preserve the return list from a different code.

**Comment by randrescastaneda** [comment]
HI JP, 

reagrding your comments. 

1. To bring the suggestion into the main file, just accept the pull request, modify it in branch dev and then merge it into the master branch. Then, you can check out again a dev branch.

2. Version could me mandatory if it refers to the version of the package. As is in you toc file, it refers to version style of the toc file. If it is v1 or v2, it does not accept smcl text. Thus, I made the defaul v 3.  You may type in STata `help usersite##remarks8` and see what I mean. 

3. My understanding is that `return add` should be used when I want to add the return list of another command that I am executing within my ado-file.  As it is now, I don't see what return list from a different code you're preserving. 

Best,

**Comment by jpazvd** [comment]
Thanks Andres.
Those are quite clear.
Best,
JP

**Pull request merged**
